# Generated by Django 4.2.16 on 2024-11-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PMFScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('score', models.FloatField()),
                ('total_responses', models.IntegerField()),
                ('segment_scores', models.JSONField(default=dict)),
                ('missing_features_analysis', models.JSONField(default=dict)),
                ('most_used_features', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('manager', 'Manager'), ('founder', 'Founder'), ('other', 'Other')], max_length=50)),
                ('disappointment_level', models.CharField(choices=[('very', 'Very disappointed'), ('somewhat', 'Somewhat disappointed'), ('not', 'Not disappointed')], max_length=20)),
                ('missing_features', models.TextField()),
                ('most_used_feature', models.CharField(max_length=100)),
                ('satisfaction_score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
