# Generated by Django 4.2.16 on 2024-12-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='occupation',
            field=models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('manager', 'Manager'), ('founder', 'Founder'), ('video_editor', 'Video Editor'), ('marketer', 'Marketer'), ('student', 'Student'), ('researcher', 'Researcher'), ('other', 'Other')], max_length=50),
        ),
    ]
