# Generated by Django 4.2.16 on 2024-12-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_survey_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payg_too_expensive', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payg_too_cheap', models.DecimalField(decimal_places=2, max_digits=5)),
                ('too_expensive', models.DecimalField(decimal_places=2, max_digits=5)),
                ('too_cheap', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expensive', models.DecimalField(decimal_places=2, max_digits=5)),
                ('annual_too_expensive', models.DecimalField(decimal_places=2, max_digits=6)),
                ('annual_bargain', models.DecimalField(decimal_places=2, max_digits=6)),
                ('preferred_plan', models.CharField(choices=[('pay_go', 'Pay As You Go'), ('monthly', 'Monthly Unlimited'), ('annual', 'Annual Unlimited')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
