# Generated by Django 4.2.16 on 2024-12-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_pricesurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='disappointment_level',
            field=models.CharField(choices=[('very_disappointed', 'Very disappointed'), ('somewhat_disappointed', 'Somewhat disappointed'), ('not_disappointed', 'Not disappointed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='survey',
            name='most_used_feature',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='satisfaction_score',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
